server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;  # Moved outside of location block
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;  # This prevents direct access to /404.html, serving it only when a 404 occurs
    }

    # Optionally handle other error pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        internal;
    }

    # Other site-specific configurations
}
